### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by greggmojica** [ParsePlatform/AnyWall#10]
When run on iOS:
(0x3179ee83 0x3baff6c7 0x3179edc5 0xbab93 0xb820d 0x9b2d3 0xb1b6d 0x86649 0x33f93aad 0x33f934f3 0x33f8db41 0x33f28a07 0x33f27cfd 0x33f8d321 0x3640776d 0x36407357 0x31769777 0x31769713 0x31767edf 0x316d2471 0x316d2253 0x33f8c5c3 0x33f87845 0x86221 0x861a8)

**Comment by hramos** [comment]
Closing. It's unclear what is being reported.
