### ISSUE TITLE
Problem podfile

### ISSUE THREAD

**Issue by daniloitj** [ParsePlatform/AnyWall#16]
Podfile not work:
Unable to find a specification for `ParseFacebookUtils''

or

Unable to find a specification for 'ParseUI'

**Comment by nlutsenko-fb** [comment]
Hmm... Just tried locally once again - and it looks like it works without any hassle...
Is there a chance you can try locally some of these steps, just to make sure there is nothing cached that might be intervening.

- Running `gem update cocoapods`
- Running `git clean -xfd .` inside checked out `AnyWall` repo folder
- Running `pod setup`
- Running `pod install` and maybe `pod update`

I hope this helps... and please let us know if it doesn't :)

**Comment by daniloitj** [comment]
follow the step by step and did not work
the error remains the same

**Comment by nlutsenko-fb** [comment]
Is there a chance you can run `pod install --verbose` and paste the full output here?
That would be super helpful to help diagnose the issue.

**Comment by daniloitj** [comment]
Analyzing dependencies

Updating spec repositories
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
  $ /usr/bin/git rev-parse  >/dev/null 2>&1
Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  error: Unable to append to .git/logs/refs/remotes/origin/master: Permission denied
  From https://github.com/CocoaPods/Specs
   ! d1011ce..ce44f18  master     -> origin/master  (unable to update local ref)

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Resolving dependencies of `Podfile`
Finished resolution (0 steps) (Took 0.002134 seconds) (2015-03-27 23:49:20 -0300)
[!] Unable to find a specification for `ParseFacebookUtils`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/resolver.rb:398:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/resolver.rb:58:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/resolver.rb:53:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:429:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:427:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:189:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by nlutsenko-fb** [comment]
I think I can see where the problem is.
This line -> `error: Unable to append to .git/logs/refs/remotes/origin/master: Permission denied`
It fails to update the cocoapods spec repo because it lacks permissions, leading to inability to find the podspecs.

If you run `pod repo` -> you should see where the `master` is located (under path).
I would suggest either removing and reading it (should reinstall in your user $HOME/.cocoapods`) or simply changing the file access rules on that folder to something like `chmod 777 $PATH_TO_REPO`.

**Comment by nlutsenko-fb** [comment]
Feel free to reopen this issue if the problem is not solved.

**Comment by daniloitj** [comment]
thanks, Work:
- sudo rm -R  ~/Library/Caches/CocoaPods
- sudo chown -R username ~/Library/Caches/CocoaPods

however the problem moved to:
ld: library not found for -lPods-Bolts
clang: error: linker command failed with exit code 1
any idea ?

**Comment by nlutsenko-fb** [comment]
It looks like you just cleaned up the cache, but `pod install` will still fail with that error (or at least I think so).

Try running `pod repo update --verbose` and making sure that succeeds. If it still doesn't - you seem to have problems with file permissions on the place where cocoapods repo is stored, not the cache.

**Comment by daniloitj** [comment]
Solve problem:
1- opening the workspace (that was generated by CocoaPods) instead of the xcodeproj
2- run again: pod install

thank you for your help

**Comment by nlutsenko-fb** [comment]
Awesome. Glad it worked.
