### ISSUE TITLE
pod install doesn't work...

### ISSUE THREAD

**Issue by pkrakow** [ParsePlatform/AnyWall#26]
...do this:

 $ gem uninstall cocoapods
 $ sudo gem install cocoapods

**Comment by hramos** [comment]
Hey @pkrakow, can you clarify? `pod install` should work if you have a working copy of CocoaPods.

**Comment by hramos** [comment]
Closing. Will reopen if we get more information.

**Comment by pkrakow** [comment]
Hector - sorry for the slow response.  I had not previously installed CocoaPods on my system (Mac Mini).  When I followed the tutorial guidance to run "pod install" I got an error message.  To ultimately get the tutorial to run I had to first run:

$ gem uninstall cocoapods
$ sudo gem install cocoapods

Then I could run the "pod install" command.

Since I hadn't installed CocoaPods before, I assumed this was a general issue (as opposed to something specific to my system).  To reproduce, you could try running through the tutorial on a fresh Mac that hasn't had CocoaPods installed.
